---
title: "Week 12: Intro to Models"
author: "Robert Dellinger"
date: "4/28/2022"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: cerulean
---

## Load Library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../output/')

library(tidyverse)
library(here)
library(palmerpenguins)
library(broom)
library(performance) 
library(modelsummary)
library(tidymodels)


```

#Anatomy of a basic linear model

```{r}


mod<-lm(y~x, data = df) #simple linear model 

mod<-lm(y~x1 + x2, data = df) #multiple regression

mod<-lm(y~x1*x2, data = df) #the * will compute x1+x2+x1:x2 (interaction term)

# Linear model of Bill depth ~ Bill length by species
Peng_mod<-lm(bill_length_mm ~ bill_depth_mm*species, data = penguins)

```

# View Results and Statistics 
```{r}
anova(Peng_mod)

summary(Peng_mod)

# Tidy coefficients
coeffs<-tidy(Peng_mod) # just put tidy() around it
coeffs

# tidy r2, etc
results<-glance(Peng_mod) 
results

# tidy residuals, etc

resid_fitted<-augment(Peng_mod)
resid_fitted
```

# Results in Model Summary
```{r}
# New model
Peng_mod_noX<-lm(bill_length_mm ~ bill_depth_mm, data = penguins)

#Make a list of models and name them
models<-list("Model with interaction" = Peng_mod,
             "Model with no interaction" = Peng_mod_noX)

#Save the results as a .docx
modelsummary(models, output = here("Week_13","output","table.docx"))
#this is a summary statistics table using R 

```

# Modelplot

```{r}

library(wesanderson)

modelplot(models) +
    labs(x = 'Coefficients', 
         y = 'Term names') +
    scale_color_manual(values = wes_palette('Darjeeling1'))

```


# Many Models with purrr, dplyr, and broom

```{r}

 models<- penguins %>%
  ungroup()%>% # the penguin data are grouped so we need to ungroup them
  nest(-species) %>% # nest all the data by species 
  mutate(fit = map(data, ~lm(bill_length_mm~body_mass_g, data = .)))

  models

models$fit # shows you each of the 3 models

 results<-models %>%
   mutate(coeffs = map(fit, tidy), # look at the coefficients
          modelresults = map(fit, glance)) %>% # R2 and others 
   select(species, coeffs, modelresults) %>% # only keep the results
   unnest() # put it back in a dataframe and specify which columns to unnest
 
 view(results) # view the results
 
 
 linear_reg()#linear regression 
 
 
 # linear regression model piped into plot 
 lm_mod<-linear_reg() %>%
  set_engine("lm") %>%
  fit(bill_length_mm ~ bill_depth_mm*species, data = penguins) %>%
  tidy() %>%
  ggplot()+
    geom_point(aes(x = term, y = estimate))+
    geom_errorbar(aes(x = term, ymin = estimate-std.error,
                      ymax = estimate+std.error), width = 0.1 )+
  coord_flip()

lm_mod
 
 
```

