---
title: "Week 8: Advanced Plotting"
author: "Robert Dellinger"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Library

```{r cars}
library(tidyverse)
library(here)
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(palmerpenguins)
```

## Patchwork and Interweaving Plots Together 

```{r, warning=FALSE}

#this section generates two plots that are separate

# plot 1

p1<-penguins%>% 
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1


# plot 2
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2


#combining plots 
cp <- p1+p2 +
  plot_layout(guides="collect")+ # merges the legends together (if they are the same)
  plot_annotation(tag_levels="A")
  
 cp 
 
cp2 <- p1/p2 + #this is a different orientation style (places on top of eachother ather then side by side)
  plot_layout(guides="collect")+ # merges the legends together (if they are the same)
  plot_annotation(tag_levels="A")
  
cp2
  
#Ccan change the themes for all graphs here if they are together (may be helpful for formatting all graphs similarly)

```
## ggrepel

```{r}

View(mtcars)


ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text() + # creates a text label
  geom_point(color = 'red')

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel them
  geom_point(color = 'red')



```

# GG Animations! gganimate()

```{r}

penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("sine-in-out") + #animation style
  ggtitle('Year: {closest_state}') + #title
  anim_save(here("Week_8","output","mypengiungif.gif"))




```


```{r}


#reading in an image
penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")
penguin

penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()

penplot<-image_read(here("Week_8","output","penguinplot.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")
out #new composite image

pengif<-image_read("https://media3.giphy.com/media/H4uE6w9G1uK4M/giphy.gif")
outgif <- image_composite(penplot, pengif, gravity = "center") #saves gif in middle of figure
animation <- image_animate(outgif, fps = 10, optimize = TRUE) #saves gif
animation



```

