---
title: "Week_5_Lab2_Plot"
author: "Robert Dellinger"
date: "2/24/2022"
output: html_document
---

```{r Library, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(beyonce)

```


```{r Read in Conductivity and Depth Data}

conductivity.data <- read_csv(here("Week_5","data", "CondData.csv")) # read in conductivity data
  
view(conductivity.data)

depth.data <- read_csv(here("Week_5","data", "DepthData.csv"))
# read in depth data 
  
view(depth.data)
```

```{r Convert Date Columns Appropriately}

conductivity.data <- conductivity.data %>% 
  mutate(datetime=mdy_hms(depth)) %>% #mutate to change a column
  rename("Date" = datetime) %>% # rename columns
  drop_na() %>%  # drop na's
  select(Date, TempInSitu, Serial, SalinityInSitu_1pCal) # select columns


depth.data <- depth.data %>% 
  mutate(datetime=ymd_hms(date)) %>% #mutate to change a column
  rename("Date" = date) %>% # rename columns
  drop_na() %>%  # drop na's
  select(Date, AbsPressure, Depth) # select columns

head(conductivity.data)

head(depth.data)
```

```{r Round the Conductivity Data to the Nearest 10 Seconds}

conductivity.data  <- conductivity.data %>% 
mutate(Date = round_date(Date, "10 seconds")) # round to nearest 10 seconds

head(conductivity.data)
head(depth.data)

```


```{r Join the Dataframes Together}

conductivity.depth<- inner_join(conductivity.data, depth.data) #inner_join() keeps the data that is complete in both data sets.

head(conductivity.depth)

```

```{r Take averages of date, depth, temperature, and salinity by minute}

conductivity.depth <- conductivity.depth %>% 
  mutate(DateByMin = round_date(Date, "minute")) %>% #round by min
  group_by(DateByMin) %>% #summarizing data by time 
  summarise(mean_date = mean(Date, na.rm = TRUE), #mean date
        mean_depth = mean(Depth, na.rm = TRUE), # mean depth
        mean_temp = mean(TempInSitu, na.rm = TRUE), # mean temp
        mean_salinity = mean(SalinityInSitu_1pCal, na.rm = TRUE)) 
        #mean salinity
            
  
  head(conductivity.depth)


```


```{r Plot using the averaged data, echo=FALSE}




plot <-conductivity.depth %>% # use conductivity.depth data
  ggplot(aes(x = mean_date, y = mean_temp)) + # date by mean temp
  geom_line()+ # draw line
  labs(title = "Mean Sea Surface Temperature Per Minute", #creating labels
       x = "Time", y = "Mean Temperature (°C)", caption = "Silbiger Unpublished")+
     scale_fill_manual(values= beyonce_palette(18))+
  theme_linedraw()+ 
  theme(title = element_text(size = 10), axis.title = element_text(size = 10), #text sizes
        panel.background = element_rect(fill = "lightcyan1")) 
        # color background
  
plot 

ggsave(here('Week_5/output', "Time_Series_Figure.png"), plot) #save plot to an output folder
  

```



